FROM ros:jazzy-ros-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions python3-argcomplete \
    build-essential git && rm -rf /var/lib/apt/lists/*

# Stay root during build & runtime (we can add a non-root later)
WORKDIR /ws

# No named user in chown; numeric is fine even if no passwd entry exists
COPY --chown=0:0 entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
