FROM ros:jazzy-ros-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions python3-argcomplete \
    build-essential git curl python3-pip \
    # Sense HAT + tools
    python3-sense-hat i2c-tools \
  && rm -rf /var/lib/apt/lists/*

# FastAPI + Uvicorn via pip (PEP 668 override OK in a container)
RUN pip3 install --no-cache-dir --break-system-packages fastapi uvicorn

WORKDIR /ws
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY run.sh /run.sh
RUN chmod +x /run.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash", "/run.sh"]
